version: "3.7"
services:
  webappvuejs:
    hostname: webappvuejs
    build: .
    ports:
      - "81:80"

  web-django:
    image: "musicshopdjango-web"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8088:8000"
